name: deploy
# on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
      - 'develop/**'
  workflow_dispatch:

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: get code
          uses: actions/checkout@v2
        - name: setup node
          uses: actions/setup-node@v2
          with:
            node-version: 20
        - name: print node version
          run: node -v
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm run test
    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: get code
          uses: actions/checkout@v2
        - name: setup node
          uses: actions/setup-node@v2
          with:
            node-version: 20
        - name: Install dependencies
          run: npm ci
        - name: Build Project
          run: npm run build
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-artifacts
            path: dist



    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-artifacts
            path: dist
        - name: Install Vercel CLI
          run: npm install -g vercel

        - name: Deploy to Vercel
          run: vercel --prod --token=$VERCEL_TOKEN --cwd=dist --confirm
          env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        
          
        
          

        
        
       
